'use client'

import Image from 'next/image'
import { Bookmark, ChevronDown, ChevronLeft, ChevronRight, ExternalLink, Pencil, Plus, RotateCcw, Trash2, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type ReactElement } from 'react'
import { type SavedItem, useSavedItems } from '@/components/saved-items'

type FolderTab = 'ideas' | 'outings'
type FolderAction = 'create' | 'rename' | 'delete' | null
const tabs: Array<{ id: FolderTab; label: string }> = [{ id: 'ideas', label: 'Saved Early Learning Ideas' }, { id: 'outings', label: 'Saved Outings & Venues' }]
const ideaTypes = ['All Types', 'Arts & Crafts', 'Outdoor & Nature', 'Sensory & STEM', 'Music, Movement & Dance', 'Literacy & Storytelling', 'Mindfulness & Wellbeing']
const ages = ['All Ages', '0–3 yrs', '3–5 yrs']; const outcomes = ['All Outcomes', 'Outcome 1 (Identity)', 'Outcome 2 (Community)', 'Outcome 3 (Wellbeing)', 'Outcome 4 (Learning)', 'Outcome 5 (Communication)']; const settings = ['All Settings', 'Indoor', 'Outdoor']; const states = ['All States', 'Victoria (VIC)', 'New South Wales (NSW)', 'Queensland (QLD)', 'Western Australia (WA)', 'Other']

export function MyFolders(): ReactElement {
  const { folders, removeSavedItem, createFolder, renameFolder, deleteFolder } = useSavedItems()
  const [tab, setTab] = useState<FolderTab>('ideas'); const [type, setType] = useState(ideaTypes[0]); const [setting, setSetting] = useState(settings[0]); const [state, setState] = useState(states[0]); const [age, setAge] = useState(ages[0]); const [outcome, setOutcome] = useState(outcomes[0]); const [folder, setFolder] = useState('__all__')
  const [action, setAction] = useState<FolderAction>(null); const [folderName, setFolderName] = useState(''); const [unsaveItem, setUnsaveItem] = useState<SavedItem | null>(null); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(8)
  useEffect(() => { const update = (): void => setPageSize(window.matchMedia('(max-width: 639px)').matches ? 4 : 8); update(); window.addEventListener('resize', update); return () => window.removeEventListener('resize', update) }, [])
  useEffect(() => { if (folder !== '__all__' && !folders.custom[folder]) setFolder('__all__') }, [folder, folders.custom])
  useEffect(() => setPage(1), [tab, type, setting, state, age, outcome, folder])
  const allLabel = tab === 'ideas' ? 'All ideas' : 'All activities'
  const selectedFolderItems = folder === '__all__' ? folders.activities : (folders.custom[folder] ?? [])
  const currentTabFolderCount = selectedFolderItems.filter((item) => tab === 'outings' ? item.id.startsWith('adventure-') : !item.id.startsWith('adventure-')).length
  const items = useMemo(() => selectedFolderItems.filter((item) => (tab === 'outings' ? item.id.startsWith('adventure-') : !item.id.startsWith('adventure-'))).filter((item) => matchesFilters(item, { tab, type, setting, state, age, outcome })), [age, selectedFolderItems, outcome, setting, state, tab, type])
  const totalPages = Math.max(1, Math.ceil(items.length / pageSize)); const visible = items.slice((page - 1) * pageSize, page * pageSize)
  const openAction = (next: Exclude<FolderAction, null>): void => { setFolderName(next === 'rename' ? folder : ''); setAction(next) }
  const confirmAction = (): void => { const name = folderName.trim(); if (action === 'create' && name) { createFolder(name); setFolder(name) }; if (action === 'rename' && name && folder !== 'Default' && folder !== '__all__') { renameFolder(folder, name); setFolder(name) }; if (action === 'delete' && folder !== 'Default' && folder !== '__all__') { deleteFolder(folder); setFolder('__all__') }; setAction(null) }
  const changeTab = (next: FolderTab): void => { setTab(next); setType(ideaTypes[0]); setSetting(settings[0]); setState(states[0]); setAge(ages[0]); setOutcome(outcomes[0]) }
  const resetView = (): void => { setFolder('__all__'); setType(ideaTypes[0]); setSetting(settings[0]); setState(states[0]); setAge(ages[0]); setOutcome(outcomes[0]); setPage(1) }
  return <main className="fixed inset-0 z-[80] overflow-y-auto bg-background"><a href="/" className="fixed right-5 top-5 z-10 inline-flex size-10 items-center justify-center rounded-full border border-border bg-card text-brand-dark shadow-sm transition-colors hover:bg-muted sm:right-8 sm:top-7" aria-label="Close My Folders"><X className="size-5" /></a><section className="mx-auto w-full px-5 pb-8 pt-20 sm:px-8 sm:pb-10 sm:pt-24 lg:w-[95%] lg:max-w-[1400px] lg:px-10 lg:pb-14 lg:pt-28"><header className="flex items-start gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Your saved workspace</p><h1 className="mt-1 font-display text-2xl font-bold text-brand-dark sm:text-3xl">My Folders</h1><p className="mt-1 text-sm text-muted-foreground">Your curated JoeyClub ideas, ready to revisit.</p></div><div className="ml-auto hidden w-[34rem] grid-cols-2 gap-1 rounded-2xl bg-muted p-1.5 lg:grid">{tabs.map((item) => <TabButton key={item.id} item={item} active={tab === item.id} onClick={() => changeTab(item.id)} />)}</div></header><div className="mt-6 grid grid-cols-2 gap-1 rounded-2xl bg-muted p-1.5 lg:hidden">{tabs.map((item) => <TabButton key={item.id} item={item} active={tab === item.id} onClick={() => changeTab(item.id)} />)}</div>
    <div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="grid w-full gap-3 sm:grid-cols-3 lg:w-2/3">{tab === 'ideas' ? <><Select label="Activity type" value={type} options={ideaTypes} onChange={setType} /><Select label="Age group" value={age} options={ages} onChange={setAge} /><Select label="EYLF outcome" value={outcome} options={outcomes} onChange={setOutcome} /></> : <><Select label="Setting" value={setting} options={settings} onChange={setSetting} /><Select label="State / region" value={state} options={states} onChange={setState} /><Select label="Age group" value={age} options={ages} onChange={setAge} /></>}</div><FolderControl folder={folder} allLabel={allLabel} folderCount={currentTabFolderCount} folders={Object.keys(folders.custom)} onChange={setFolder} onCreate={() => openAction('create')} onRename={() => openAction('rename')} onDelete={() => openAction('delete')} /></div>
    <div className="mt-7 flex items-center justify-start gap-2"><span className="rounded-full bg-badge-yellow px-3 py-1.5 text-sm font-bold text-badge-yellow-foreground">{folder === '__all__' ? allLabel : folder}</span><div className="group relative"><button type="button" onClick={resetView} aria-label="Clear all filters and reset folder" className="inline-flex size-8 items-center justify-center rounded-full border border-border bg-card text-primary shadow-sm transition-colors hover:bg-muted"><RotateCcw className="size-4" /></button><span className="pointer-events-none absolute left-[calc(100%+0.45rem)] top-1/2 z-20 hidden -translate-y-1/2 whitespace-nowrap rounded-md bg-brand-dark px-2 py-1 text-[0.7rem] font-semibold text-white shadow-sm group-hover:block">Clear all / Reset</span></div></div>{visible.length === 0 ? <div className="mt-3 rounded-xl border border-dashed border-border bg-card/60 px-5 py-14 text-center text-muted-foreground">No saved activities in {folder === '__all__' ? allLabel : folder} match these filters yet.</div> : <div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visible.map((item) => <SavedItemCard key={`${item.type}-${item.id}`} item={item} folder={folder === '__all__' ? folderForItem(item, folders.custom) : folder} onRemove={() => setUnsaveItem(item)} />)}</div>}{totalPages > 1 && <Pagination page={page} totalPages={totalPages} onChange={setPage} />}
  </section>{action && <FolderActionDialog action={action} name={folderName} isDefault={folder === 'Default' || folder === '__all__'} onNameChange={setFolderName} onConfirm={confirmAction} onClose={() => setAction(null)} />}{unsaveItem && <UnsaveDialog item={unsaveItem} onConfirm={() => { removeSavedItem(unsaveItem); setUnsaveItem(null) }} onClose={() => setUnsaveItem(null)} />}</main>
}

function TabButton({ item, active, onClick }: { item: { id: FolderTab; label: string }; active: boolean; onClick: () => void }): ReactElement { return <button type="button" onClick={onClick} className={`rounded-xl px-4 py-3 text-sm font-bold ${active ? 'bg-primary text-primary-foreground shadow-sm' : 'text-foreground/75 hover:text-primary'}`}>{item.label}</button> }
function FolderControl({ folder, allLabel, folderCount, folders, onChange, onCreate, onRename, onDelete }: { folder: string; allLabel: string; folderCount: number; folders: string[]; onChange: (folder: string) => void; onCreate: () => void; onRename: () => void; onDelete: () => void }): ReactElement { const disabled = folder === 'Default' || folder === '__all__'; const options = [{ value: '__all__', label: allLabel }, ...folders.map((name) => ({ value: name, label: name }))]; const label = folder === '__all__' ? `${allLabel} · ${folderCount} saved` : `${folder} · ${folderCount} saved`; return <div className="flex min-w-[22rem] items-center gap-2 self-start lg:ml-auto lg:min-w-[20rem] lg:self-auto"><MenuSelect value={folder} options={options} onChange={onChange} ariaLabel="Switch folder" buttonLabel={label} compact /><IconButton label="Delete folder" onClick={onDelete} disabled={disabled}><Trash2 className="size-4" /></IconButton><IconButton label="Rename folder" onClick={onRename} disabled={disabled}><Pencil className="size-4" /></IconButton><IconButton label="Create folder" onClick={onCreate}><Plus className="size-4" /></IconButton></div> }
function IconButton({ label, onClick, children, disabled = false }: { label: string; onClick: () => void; children: ReactElement; disabled?: boolean }): ReactElement { return <button type="button" onClick={onClick} disabled={disabled} aria-label={label} className="inline-flex size-11 shrink-0 items-center justify-center rounded-full border border-border bg-card text-primary shadow-sm transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-35">{children}</button> }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }): ReactElement { return <label className="text-sm font-semibold text-brand-dark"><span className="mb-1 block text-[0.68rem] uppercase tracking-wide text-muted-foreground">{label}</span><MenuSelect value={value} options={options.map((option) => ({ value: option, label: option }))} onChange={onChange} ariaLabel={label} /></label> }
function MenuSelect({ value, options, onChange, ariaLabel, buttonLabel, compact = false }: { value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void; ariaLabel: string; buttonLabel?: string; compact?: boolean }): ReactElement { const [open, setOpen] = useState(false); const ref = useRef<HTMLDivElement>(null); useEffect(() => { const close = (event: MouseEvent): void => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, []); const label = buttonLabel ?? options.find((option) => option.value === value)?.label ?? value; return <div ref={ref} className="relative min-w-0 flex-1"><button type="button" onClick={() => setOpen((current) => !current)} aria-expanded={open} aria-label={ariaLabel} className={`flex w-full items-center justify-between rounded-lg border border-primary bg-card px-4 text-left text-sm font-semibold text-brand-dark shadow-sm ${compact ? 'h-11' : 'py-2.5'}`}><span className="truncate">{label}</span><ChevronDown className={`size-4 shrink-0 text-primary transition-transform ${compact ? 'ml-4' : ''} ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="absolute left-0 right-0 z-30 mt-2 overflow-hidden rounded-lg border border-border bg-card p-1.5 shadow-[0_18px_38px_-20px_rgba(63,81,54,0.55)]">{options.map((option) => <button key={option.value} type="button" onClick={() => { onChange(option.value); setOpen(false) }} className={`block w-full rounded-md px-4 py-2.5 text-left text-sm transition-colors hover:bg-[#EDF3E8] ${option.value === value ? 'bg-[#DCE8D2] font-semibold text-brand-dark' : 'text-brand-dark'}`}>{option.label}</button>)}</div>}</div> }
function SavedItemCard({ item, folder, onRemove }: { item: SavedItem; folder: string; onRemove: () => void }): ReactElement { return <article className="flex min-w-0 flex-col rounded-2xl border border-border bg-card p-4 shadow-[0_16px_36px_-28px_rgba(63,81,54,0.4)]"><span className="mb-2 w-fit rounded-full bg-badge-yellow px-2.5 py-1 text-[0.7rem] font-bold text-badge-yellow-foreground">{folder}</span><div className="grid grid-cols-2 items-center gap-3"><div className="relative aspect-[4/3] overflow-hidden rounded-xl bg-cream">{item.image ? <Image src={item.image} alt="" fill className="object-cover" /> : <Bookmark className="absolute inset-0 m-auto size-8 text-primary/60" />}</div><div className="min-w-0"><p className="line-clamp-2 font-display text-base font-bold leading-tight text-brand-dark">{item.title}</p><div className="mt-2 flex min-w-0 flex-col items-start gap-1 overflow-hidden">{item.tags?.slice(0, 2).map((tag) => <span key={tag} title={tag} className="block max-w-full truncate whitespace-nowrap rounded-full bg-badge-green px-2 py-1 text-[0.68rem] font-semibold">{tag}</span>)}</div></div></div><p className="mt-3 line-clamp-2 text-sm leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-3 flex items-center justify-between gap-2 border-t border-border pt-3">{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-primary underline underline-offset-4">Visit site <ExternalLink className="size-3.5" /></a>}<button type="button" onClick={onRemove} className="text-sm font-bold text-[#A85C4D] hover:underline">Unsave</button></div></article> }
function folderForItem(item: SavedItem, folders: Record<string, SavedItem[]>): string { return Object.entries(folders).find(([, saved]) => saved.some((entry) => entry.id === item.id))?.[0] ?? 'Default' }
function FolderActionDialog({ action, name, isDefault, onNameChange, onConfirm, onClose }: { action: Exclude<FolderAction, null>; name: string; isDefault: boolean; onNameChange: (value: string) => void; onConfirm: () => void; onClose: () => void }): ReactElement { const isDelete = action === 'delete'; const title = action === 'create' ? 'Create a folder' : isDelete ? 'Delete this folder?' : 'Rename folder'; return <div className="fixed inset-0 z-[90] grid place-items-center bg-brand-dark/30 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-sm rounded-xl border border-border bg-background p-5 shadow-2xl"><h2 className="font-display text-xl font-bold text-brand-dark">{title}</h2>{isDelete ? <p className="mt-2 text-sm leading-relaxed text-muted-foreground">This removes the folder only. Your saved activities stay available in Default.</p> : <input autoFocus value={name} onChange={(event) => onNameChange(event.target.value)} placeholder="Folder name" className="mt-4 w-full rounded-lg border border-primary bg-card px-3 py-2.5 text-sm outline-none" />}{isDefault && <p className="mt-2 text-sm text-[#A85C4D]">Default cannot be renamed or deleted.</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-sm font-bold text-muted-foreground">Cancel</button><button type="button" disabled={isDefault} onClick={onConfirm} className={`rounded-lg px-3 py-2 text-sm font-bold text-white ${isDelete ? 'bg-[#A85C4D]' : 'bg-primary'} disabled:opacity-40`}>{isDelete ? 'Yes, delete' : 'Confirm'}</button></div></div></div> }
function UnsaveDialog({ item, onConfirm, onClose }: { item: SavedItem; onConfirm: () => void; onClose: () => void }): ReactElement { return <div className="fixed inset-0 z-[90] grid place-items-center bg-brand-dark/30 p-4" role="dialog" aria-modal="true" aria-labelledby="unsave-dialog-title"><div className="w-full max-w-sm rounded-xl border border-border bg-background p-5 shadow-2xl"><h2 id="unsave-dialog-title" className="font-display text-xl font-bold leading-snug text-brand-dark">Are you sure you want to unsave “{item.title}”?</h2><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-bold text-muted-foreground transition-colors hover:bg-muted">No</button><button type="button" onClick={onConfirm} className="rounded-lg bg-[#A85C4D] px-4 py-2.5 text-sm font-bold text-white transition-colors hover:bg-[#914C40]">Yes</button></div></div></div> }
function matchesFilters(item: SavedItem, filters: { tab: FolderTab; type: string; setting: string; state: string; age: string; outcome: string }): boolean { const itemAge = item.ageGroup === 'Toddlers' ? '0–3 yrs' : '3–5 yrs'; const tag = item.tags?.[0]?.toLowerCase() ?? ''; const matchesType = filters.tab === 'outings' || filters.type === 'All Types' || (filters.type === 'Outdoor & Nature' ? /outdoor|nature|physical/.test(tag) : filters.type === 'Sensory & STEM' ? /sensory|stem/.test(tag) : filters.type === 'Music, Movement & Dance' ? /music|movement|dance/.test(tag) : filters.type === 'Mindfulness & Wellbeing' ? /wellbeing|social-emotional/.test(tag) : tag.includes(filters.type.split(' ')[0].toLowerCase())); const text = `${item.title} ${item.description ?? ''}`.toLowerCase(); const detectedState = text.includes('sydney') ? 'New South Wales (NSW)' : text.includes('brisbane') ? 'Queensland (QLD)' : text.includes('perth') ? 'Western Australia (WA)' : /vic|victoria|melbourne|kew/.test(text) ? 'Victoria (VIC)' : 'Other'; return matchesType && (filters.tab === 'ideas' || filters.setting === 'All Settings' || item.environment === filters.setting) && (filters.tab === 'ideas' || filters.state === 'All States' || detectedState === filters.state) && (filters.age === 'All Ages' || itemAge === filters.age) && (filters.outcome === 'All Outcomes' || item.eylfOutcomes.some((value) => filters.outcome.startsWith(value))) }
function Pagination({ page, totalPages, onChange }: { page: number; totalPages: number; onChange: (page: number) => void }): ReactElement { return <nav className="mt-7 flex items-center justify-center gap-2"><button type="button" onClick={() => onChange(Math.max(1, page - 1))} disabled={page === 1} className="inline-flex size-9 items-center justify-center rounded-full border border-border bg-card text-primary disabled:opacity-40"><ChevronLeft className="size-4" /></button><span className="text-sm font-semibold text-muted-foreground sm:hidden">Page {page} of {totalPages}</span><div className="hidden items-center gap-1 sm:flex">{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <button key={number} type="button" onClick={() => onChange(number)} className={`flex size-9 items-center justify-center rounded-full text-sm font-bold ${page === number ? 'bg-primary text-primary-foreground' : 'text-foreground/70 hover:bg-muted'}`}>{number}</button>)}</div><button type="button" onClick={() => onChange(Math.min(totalPages, page + 1))} disabled={page === totalPages} className="inline-flex size-9 items-center justify-center rounded-full border border-border bg-card text-primary disabled:opacity-40"><ChevronRight className="size-4" /></button></nav> }
