'use client'

import { useEffect, useRef, useState, type ReactElement } from 'react'
import { Bookmark, ChevronDown, X } from 'lucide-react'
import { useSavedItems } from '@/components/saved-items'

export function SaveToFolderDialog(): ReactElement | null {
  const { folders, pendingActivity, createFolder, assignPendingActivity, dismissPendingActivity } = useSavedItems()
  const [selected, setSelected] = useState('Default')
  const [newFolder, setNewFolder] = useState('')
  const [open, setOpen] = useState(false)
  const pickerRef = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (event: MouseEvent): void => { if (pickerRef.current && !pickerRef.current.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  if (!pendingActivity) return null
  const createAndSelect = (): void => { const name = newFolder.trim(); if (!name) return; createFolder(name); setSelected(name); setNewFolder('') }
  const folderNames = Object.keys(folders.custom)
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-brand-dark/30 p-4" role="dialog" aria-modal="true" aria-labelledby="save-folder-title"><div className="w-full max-w-md rounded-2xl border border-border bg-background p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex size-9 items-center justify-center rounded-full bg-badge-green text-primary"><Bookmark className="size-5 fill-current" /></span><h2 id="save-folder-title" className="mt-3 font-display text-2xl font-bold text-brand-dark">Save to a folder?</h2><p className="mt-1 text-sm leading-relaxed text-muted-foreground">“{pendingActivity.title}” is saved. Choose where you would like to keep it.</p></div><button type="button" onClick={dismissPendingActivity} className="inline-flex size-9 shrink-0 items-center justify-center rounded-full border border-border bg-card text-brand-dark shadow-sm transition-colors hover:bg-muted" aria-label="Keep in Default folder"><X className="size-4" /></button></div><label className="mt-5 block text-xs font-bold uppercase tracking-wide text-brand-dark">Folder</label><div ref={pickerRef} className="relative mt-1.5"><button type="button" onClick={() => setOpen((current) => !current)} aria-expanded={open} className="flex w-full items-center justify-between rounded-xl border border-primary bg-card px-5 py-3 text-left text-sm font-semibold text-brand-dark"><span>{selected}</span><ChevronDown className={`size-4 text-primary transition-transform ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="absolute left-0 right-0 z-20 mt-2 overflow-hidden rounded-xl border border-border bg-card p-1.5 shadow-[0_18px_38px_-20px_rgba(63,81,54,0.55)]">{folderNames.map((name) => <button key={name} type="button" onClick={() => { setSelected(name); setOpen(false) }} className={`block w-full rounded-lg px-4 py-2.5 text-left text-sm transition-colors hover:bg-[#EDF3E8] ${name === selected ? 'bg-[#DCE8D2] font-semibold text-brand-dark' : 'text-brand-dark'}`}>{name}</button>)}</div>}</div><div className="mt-4 flex items-center gap-3"><input value={newFolder} onChange={(event) => setNewFolder(event.target.value)} placeholder="Create a new folder" className="min-w-0 flex-1 rounded-lg border border-border bg-card px-3 py-2 text-sm outline-none" /><button type="button" onClick={createAndSelect} className="shrink-0 px-1 text-sm font-bold text-primary underline decoration-1 underline-offset-4 hover:text-brand-dark">Create</button></div><div className="mt-5 flex justify-end"><button type="button" onClick={() => assignPendingActivity(selected)} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Confirm</button></div></div></div>
}
